env:
  browser: true
  es2021: true
  node: true
extends:
  - eslint-config-next
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
  - plugin:react-hooks/recommended
  - plugin:promise/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - '@typescript-eslint'
  - no-relative-import-paths
  - react
  - prettier
  - react-refresh
  - promise
  - import
ignorePatterns:
  - 'next-env.d.ts'
  - 'docs/**/*'
rules:
  'react-hooks/exhaustive-deps': 'off'
  '@next/next/no-img-element': 'off'
  'prettier/prettier': ['error', { 'endOfLine': 'auto' }]
  '@typescript-eslint/no-explicit-any': 'off'
  '@typescript-eslint/ban-ts-comment': 'off'
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-unsafe-argument': 'off'
  '@typescript-eslint/strict-boolean-expressions': 'off'
  '@typescript-eslint/no-misused-promises': 'off'
  '@typescript-eslint/no-floating-promises': 'off'
  '@typescript-eslint/restrict-template-expressions': 'off'
  'no-relative-import-paths/no-relative-import-paths':
    ['error', { 'allowSameFolder': true }]
  'no-console': 'error'
  '@typescript-eslint/promise-function-async': 'off'
  'react-refresh/only-export-components': 'warn'
  'react/react-in-jsx-scope': 'off'
settings:
  'import/parsers': { '@typescript-eslint/parser': ['.ts', '.tsx'] }
  'import/resolver': { 'typescript': { 'alwaysTryTypes': true } }
  'import/no-named-as-default': 'off'
  'react-refresh/only-export-components': 'off'
