singleQuote: true
importOrder:
  [
    '^react$',
    '^next/(.*)$',
    '<THIRD_PARTY_MODULES>',
    '^@/entities/(.*)$',
    '^@/features/(.*)$',
    '^@/widgets/(.*)$',
    '^@/shared/(.*)$',
    '^@/(.*)$',
    '^app/(.*)$',
    '^[./]',
  ]
importOrderSeparation: true
importOrderSortSpecifiers: true
importOrderCaseInsensitive: true
plugins: ['@trivago/prettier-plugin-sort-imports']
